- index: 1
   name: DAPI
   marker: "-"
   biological_role: "核染色"
   is_dapi: true
 - index: 2
   name: Opal480
   marker: CD20
   biological_role: "细胞质"
 - index: 3
   name: Opal520
   marker: CD3
   biological_role: "细胞膜"
 - index: 4
   name: Opal570
   marker: FOXP3
   biological_role: "细胞核"
 - index: 5
   name: Opal620
   marker: CD23
   biological_role: "细胞核"
 - index: 6
   name: Opal690
   marker: CD8
   biological_role: "细胞膜"
 - index: 7
   name: Opal780
   marker: PAX8s
   biological_role: "细胞核"
 - index: 8
   name: SampleAF
   marker: AF
   biological_role: "细胞自发荧光（背景）"
   is_af: true